### ISSUE TITLE
Thank you good sir

### ISSUE THREAD

**Issue by alicektx** [tinkershack/fluffy#14]
..."Reports events faithfully.
There are popular libraries/tools built already that do a poor job at reporting the events..."

Lost a good amount of time (and almost my...hope),
fiddling around with this or that or the other - no names needed.
What the heck...

No real 'issue' here (hence closing it asap), 
but after the frustration, for whatever it's worth it,
i just felt the need of saying 'thank you': simple in it's usage, 
clear & end-user friendly in it's displayed results, it simply...delivers. :thumbsup: :v:

**Comment by raamsri** [comment]
@alicektx Cheers mate! Happy to help ;)
